# http -> https
[[redirects]]
  from = "http://lowentech.dev/*"
  to = "https://lowentech.dev/:splat"
  status = 301
  force = true

# www -> non-www (tek host)
[[redirects]]
  from = "https://www.lowentech.dev/*"
  to = "https://lowentech.dev/:splat"
  status = 301
  force = true

# /index.html -> /  (ana sayfa varyantını kapat)
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# tercihini seç: slashsız URL'ler ( /about/ -> /about )
[[redirects]]
  from = "/:path/"
  to = "/:path"
  status = 301
  conditions = {Language = ["en"]} # şart değil; kaldırabilirsin

# SPA rewrite (redirect DEĞİL, 200 olmalı)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
